"""
Django settings for portfolio project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path



# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# 1. SECURITY FIX: Gamitin ang Environment Variable para sa SECRET_KEY
# Ito ay para sa seguridad. Ilagay ito sa Render bilang Environment Variable.
# Kung gagamit ka ng .env file locally, lalabas ito.
SECRET_KEY = os.environ.get('SECRET_KEY', 'default-insecure-key')

# 2. SECURITY FIX: I-set ang DEBUG sa False sa Production
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True' # Pwedeng i-override sa Render

ALLOWED_HOSTS = [
    '127.0.0.1', 
    'localhost', 
    'castillo-parungo-portfolio.onrender.com'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Idagdag ang iyong custom apps dito (e.g., 'myapp')
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # 3. WHITENOISE FIX: Dapat nasa ilalim ng SecurityMiddleware ito!
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'portfolio.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio.wsgi.application'

# Database configuration (OK na ito)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# ... (Iba pang settings: Password Validation, I18N, TIME_ZONE, OK na) ...

# 4. STATIC FILES FIX: Idagdag ang mga kailangan para sa Whitenoise sa Production
STATIC_URL = 'static/'

# Folder kung saan mo inilalagay ang iyong static assets (CSS/Images)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Dito kokolektahin ni Django ang lahat ng static files (Kailangan ng Render!)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Storage para sa caching at compression (Optimized for Whitenoise)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'